import type { Fountain } from "../types/fountain";

export const mockFountains: Fountain[] = [
  {
    id: 1,
    name: "Starbucks Water Fountain",
    latitude: 28.1235,
    longitude: -15.4363,
    description: "High quality filtered water fountain located at the entrance",
    isOperational: true,
    distance: "1.8 km Away",
    rating: 4.8,
    isFree: true,
    category: "Popular",
  },
  {
    id: 2,
    name: "Joe's Park Water Fountain",
    latitude: 28.135,
    longitude: -15.43,
    description: "Natural spring water fountain in the park",
    isOperational: true,
    distance: "5.2 km Away",
    rating: 4.8,
    isFree: true,
  },
  {
    id: 3,
    name: "Steves backyard stream",
    latitude: 28.132,
    longitude: -15.425,
    description: "Private backyard natural stream water source",
    isOperational: true,
    distance: "2.5 km Away",
    rating: 4.8,
    isFree: true,
  },
  {
    id: 4,
    name: "No mans land",
    latitude: 28.138,
    longitude: -15.428,
    description: "Remote location water source",
    isOperational: false,
    distance: "8.1 km Away",
    rating: 3.5,
    isFree: false,
  },
  {
    id: 5,
    name: "Gullfoss",
    latitude: 64.32713999644166,
    longitude: -20.119973219271998,
    description: "Iconic waterfall and water source at Gullfoss",
    isOperational: true,
    rating: 4.9,
    isFree: true,
    category: "Popular",
  },
  {
    id: 6,
    name: "Glacier Spring",
    latitude: 65.324,
    longitude: -14.545,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 7,
    name: "Northern Fjord Lake",
    latitude: 66.15,
    longitude: -18.125,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 8,
    name: "Eastern River Bend",
    latitude: 65.1,
    longitude: -13.85,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 9,
    name: "South Coast Lagoon",
    latitude: 63.95,
    longitude: -20.3,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 10,
    name: "Western Highland Pool",
    latitude: 64.75,
    longitude: -23.45,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 11,
    name: "Central Highlands Pond",
    latitude: 64.55,
    longitude: -19.7,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 12,
    name: "Reykjanes Stream",
    latitude: 63.89,
    longitude: -22.05,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 13,
    name: "Westfjords Bay Inlet",
    latitude: 66.03,
    longitude: -23.25,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 14,
    name: "North Jutland Spring",
    latitude: 57.1,
    longitude: 10.3,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 15,
    name: "Funen Forest Lake",
    latitude: 55.35,
    longitude: 10.1,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 16,
    name: "Zealand River Crossing",
    latitude: 55.6,
    longitude: 12,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 17,
    name: "South Denmark Marsh",
    latitude: 54.9,
    longitude: 9.8,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 18,
    name: "Bornholm Coastal Pool",
    latitude: 55.15,
    longitude: 15.15,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 19,
    name: "Limfjord Waterhole",
    latitude: 56.9,
    longitude: 8.6,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 20,
    name: "East Jutland Brook",
    latitude: 56.3,
    longitude: 10.7,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
  {
    id: 21,
    name: "West Zealand Pond",
    latitude: 55.4,
    longitude: 11.1,
    isOperational: true,
    isFree: true,
    rating: 4.5,
  },
];
